services:
  site_monitor:
    container_name: site_monitor
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./db.sqlite:/app/db.sqlite
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3, os; sqlite3.connect(os.getenv('DB_FILE','/app/db.sqlite')).execute('SELECT 1')"]
      interval: 30s
      timeout: 10s
      retries: 3
